spring:
  application:
    name: kdg_backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost:${DB_PORT:54321}/${DB_NAME:kdg_db}}
    username: ${DB_USER:kdg_user}
    password: ${DB_PASSWORD:kdg_pass}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: "file:infrastructure/init-scripts/schema-creation.sql"



