services:

  kdg_db:
    image: postgres:16.1-alpine
    container_name: kdg_db
    restart: always
    environment:
      POSTGRES_DB: kdg_db
      POSTGRES_USER: kdg_user
      POSTGRES_PASSWORD: kdg_pass
    ports:
      - "54321:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  app_rabbitmq:
    image: rabbitmq:3.13.7-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'password'
    ports:
      - "5672:5672" #AMQP
      - "15672:15672" #MGMT
    networks:
      - backend
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq/

  delivery_service:
    image: registry.gitlab.com/kdg-ti/programming6/material/2025-2026/delivery-service
    environment:
      SPRING_PROFILES_ACTIVE: 'docker'
      SPRING_RABBITMQ_HOST: 'app_rabbitmq'
    pull_policy: "always"
    ports:
      - "8095:8095"
    networks:
      - backend


  idp_postgres:
    image: postgres:17.6-alpine
    volumes:
      - ./idp/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - backend

  idp_keycloak:
    image: quay.io/keycloak/keycloak:26.3
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=idp_postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
    command: start-dev
    ports:
      - "8180:8080"
    depends_on:
      - idp_postgres
    networks:
      - backend

networks:
  backend:
    driver: bridge
